name = "tennis-league-client"
main = "worker.js"
compatibility_date = "2025-05-07"

account_id = "" # Fill in your Cloudflare account ID here

[site]
bucket = "./dist"

[build]
command = "npm run build:worker"
upload.format = "service-worker"

[env.production]
workers_dev = false
# route = "example.com/*" # Add your domain here when deploying to production

[env.development]
workers_dev = true