[site]
bucket = "./dist"
entry-point = "."

name = "tennis-league"
type = "webpack"
account_id = "" # You'll need to fill in your Cloudflare account ID here

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
workers_dev = false
# route = "" # Add your production route if needed

[env.development]
workers_dev = true